name: Upload, build and start bot
run-name: ${{ github.actor }} just updated the bot
on:
  - push
jobs:
  Upload-Build-Run:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Push
        uses: ErenKrt/ssh-push@cea145c9f5cc7a0a12e8151ac946e6d2fe565fd7
        with:
          host: ${{ secrets.SINUS_BOT_SFTP_HOST }}
          port: 22
          username: ${{ secrets.SINUS_BOT_SFTP_USER }}
          password: ${{ secrets.SINUS_BOT_SFTP_PASS }}
          source: "./"
          destination: ${{ secrets.SINUS_BOT_SFTP_PATH }}
          scripts: |
            npm install
            npm run build
            sudo systemctl restart sinusbot
