name: Upload, build and start bot
run-name: ${{ github.actor }} just updated the bot
on:
  - push
jobs:
  Upload-Build-Run:
    runs-on: ubuntu-latest
    steps:
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SINUS_BOT_SFTP_HOST }}
          username: ${{ secrets.SINUS_BOT_SFTP_USER }}
          password: ${{ secrets.SINUS_BOT_SFTP_PASS }}
          port: 22
          uploads: |
            ./ => /home/sinus-bot/
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SINUS_BOT_SFTP_HOST }}
          username: ${{ secrets.SINUS_BOT_SFTP_USER }}
          password: ${{ secrets.SINUS_BOT_SFTP_PASS }}
          port: 22
          script: |
            cd /home/sinus-bot
            npm install
            npm run build
            sudo systemctl restart sinusbot
