name: Upload, build and start bot
run-name: ${{ github.actor }} just updated the bot
on:
  - push
jobs:
  Upload-Build-Run:
    runs-on: ubuntu-latest
    steps:
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SINUS_BOT_SFTP_HOST }}
          username: ${{ secrets.SINUS_BOT_SFTP_USER }}
          password: ${{ secrets.SINUS_BOT_SFTP_PASS }}
          port: 22
          uploads: |
            ./assets/ => ${{ secrets.SINUS_BOT_SFTP_PATH }}/assets/
            ./src/ => ${{ secrets.SINUS_BOT_SFTP_PATH }}/src/
            ./tsconfig.json => ${{ secrets.SINUS_BOT_SFTP_PATH }}/tsconfig.json
            ./package.json => ${{ secrets.SINUS_BOT_SFTP_PATH }}/package.json
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SINUS_BOT_SFTP_HOST }}
          username: ${{ secrets.SINUS_BOT_SFTP_USER }}
          password: ${{ secrets.SINUS_BOT_SFTP_PASS }}
          port: 22
          script: |
            npm install
            npm run build
            sudo systemctl restart sinusbot
